- name: install wget
  yum: name='wget' state=installed
  sudo: yes

- name: download epel rpm
  shell: "wget --no-check-certificate http://download.fedoraproject.org/pub/epel/6/x86_64/{{ epel_filename }} -O {{ epel_rpm }} creates={{ epel_rpm }}"

- name: yum install epel (Extra Packages for Enterprise Linux)
  shell: "yum -y --nogpgcheck localinstall {{ epel_rpm }}"
  sudo: yes

- name: git
  yum: name='git' state=installed
  sudo: yes

- name: yum install python-pip
  yum: name='python-pip' state=installed
  sudo: yes

#- name: easy_install
  #yum: name='python-distribute' state=installed
  #sudo: yes

#- name: install pip
  #easy_install: name='pip'
  #sudo: yes

- name: install argparse for python
  pip: name='argparse' state=present
  sudo: yes

- name: install tmux
  yum: name='tmux' state=installed
  sudo: yes

- name: install lsof
  yum: name='lsof' state=installed
  sudo: yes

- name: install ntp
  yum: name={{item}} state=installed
  with_items:
    - ntp
    - ntpdate.x86_64
  sudo: yes

- name: Ensure ntpd is on via chkconfig
  shell: chkconfig ntpd on
  sudo: yes
