---
:intnetName: neverwinterDP
machines:
- name: sparkngin1
  url: demandcube/centos-65_x86_64-VB-4.3.8
- name: sparkngin2
  url: demandcube/centos-65_x86_64-VB-4.3.8
- name: jenkinsdp
  url: demandcube/centos-65_x86_64-VB-4.3.8
