# Example using tags to conditionally only set certain roles
# - hosts: all
#   roles:
#     - common
#     - { role: nginx, tags: ['base'] }
#     - { role: sparkngin, tags: ['sparkngin'] }
#     - { role: zookeeper, tags: ['zookeeper'] }
#     - { role: kafka, tags: ['kafka'] }

- hosts: sparkngin1
  roles:
    - test
    - common
    - sparkngin

- hosts: sparkngin2
  roles:
    - test
    - common
    - java
    - zookeeper
    - kafka

    

