# Example using tags to conditionally only set certain roles
# - hosts: all
#   roles:
#     - common
#     - { role: nginx, tags: ['base'] }
#     - { role: sparkngin, tags: ['sparkngin'] }
#     - { role: zookeeper, tags: ['zookeeper'] }
#     - { role: kafka, tags: ['kafka'] }

- hosts: sparkngin1
  roles:
    - test
    - common
    - sparkngin
    - testing_tools

- hosts: sparkngin2
  roles:
    - test
    - common
    - java
    - zookeeper
    - kafka
    - testing_tools
    - play-framework
    - mysql-server
    - kafka-web-console
    - kafka-offset-monitor
